# Generated by Django 4.0.4 on 2022-07-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='date',
            new_name='Date',
        ),
    ]
